### ISSUE TITLE
macOS-homebrew-installed primersearch works on the example code

### ISSUE THREAD

**Issue by dougwyu** [grunwaldlab/metacoder#171]
I ran your example code successfully on a macOS installation, having used homebrew to install primersearch

## Not run: 
result <- primersearch(rdp_ex_data, 
                       forward = c("U519F" = "CAGYMGCCRCGGKAAHACC"),
                       reverse = c("Arch806R" = "GGACTACNSGGGTMTCTAAT"),
                       mismatch = 10)
                       
heat_tree(result, 
          node_size = n_obs,
          node_label = name,
          node_color = prop_amplified,
          node_color_range = c("red", "yellow", "green"),
          node_color_trans = "linear",
          node_color_interval = c(0, 1),
          layout = "fruchterman-reingold")

**Comment by zachary-foster** [comment]
Thanks @dougwyu! I will change the documentation accordingly.
