### ISSUE TITLE
dev version not installable

### ISSUE THREAD

**Issue by dougwyu** [grunwaldlab/metacoder#172]
`devtools::install_github("grunwaldlab/metacoder@dev")`

> Downloading GitHub repo grunwaldlab/metacoder@dev
> from URL https://api.github.com/repos/grunwaldlab/metacoder/zipball/dev
> Installing metacoder
> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
>   --no-save --no-restore --quiet CMD INSTALL  \
>   '/private/var/folders/4g/4wpmdzbd7tj0cwctcd99wz680000gn/T/RtmpC2KgRc/devtoolse5834c8dc233/grunwaldlab-metacoder-89e4c01'  \
>   --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
>   --install-tests 
> 
> \* installing *source* package ‘metacoder’ ...
> ** R
> ** data
> *** moving datasets to lazyload DB
> Warning: S3 methods ‘extract_taxonomy.DNAbin’, ‘extract_taxonomy.default’, ‘extract_taxonomy.list’, ‘print.taxmap’ were declared in NAMESPACE but not found
> Warning: namespace ‘metacoder’ is not available and has been replaced
> by .GlobalEnv when processing object ‘bryophytes_ex_data’
> Warning: S3 methods ‘extract_taxonomy.DNAbin’, ‘extract_taxonomy.default’, ‘extract_taxonomy.list’, ‘print.taxmap’ were declared in NAMESPACE but not found
> Warning: namespace ‘metacoder’ is not available and has been replaced
> by .GlobalEnv when processing object ‘bryophytes_ex_data’
> Warning: S3 methods ‘extract_taxonomy.DNAbin’, ‘extract_taxonomy.default’, ‘extract_taxonomy.list’, ‘print.taxmap’ were declared in NAMESPACE but not found
> Warning: namespace ‘metacoder’ is not available and has been replaced
> by .GlobalEnv when processing object ‘contaminants’
> Warning: S3 methods ‘extract_taxonomy.DNAbin’, ‘extract_taxonomy.default’, ‘extract_taxonomy.list’, ‘print.taxmap’ were declared in NAMESPACE but not found
> Warning: namespace ‘metacoder’ is not available and has been replaced
> by .GlobalEnv when processing object ‘contaminants’
> Warning: S3 methods ‘extract_taxonomy.DNAbin’, ‘extract_taxonomy.default’, ‘extract_taxonomy.list’, ‘print.taxmap’ were declared in NAMESPACE but not found
> Warning: namespace ‘metacoder’ is not available and has been replaced
> by .GlobalEnv when processing object ‘genbank_ex_data’
> Warning: S3 methods ‘extract_taxonomy.DNAbin’, ‘extract_taxonomy.default’, ‘extract_taxonomy.list’, ‘print.taxmap’ were declared in NAMESPACE but not found
> Warning: namespace ‘metacoder’ is not available and has been replaced
> by .GlobalEnv when processing object ‘genbank_ex_data’
> Warning: S3 methods ‘extract_taxonomy.DNAbin’, ‘extract_taxonomy.default’, ‘extract_taxonomy.list’, ‘print.taxmap’ were declared in NAMESPACE but not found
> Warning: namespace ‘metacoder’ is not available and has been replaced
> by .GlobalEnv when processing object ‘its1_ex_data’
> Warning: S3 methods ‘extract_taxonomy.DNAbin’, ‘extract_taxonomy.default’, ‘extract_taxonomy.list’, ‘print.taxmap’ were declared in NAMESPACE but not found
> Warning: namespace ‘metacoder’ is not available and has been replaced
> by .GlobalEnv when processing object ‘its1_ex_data’
> Warning: S3 methods ‘extract_taxonomy.DNAbin’, ‘extract_taxonomy.default’, ‘extract_taxonomy.list’, ‘print.taxmap’ were declared in NAMESPACE but not found
> Warning: namespace ‘metacoder’ is not available and has been replaced
> by .GlobalEnv when processing object ‘pr2_ex_data’
> Warning: S3 methods ‘extract_taxonomy.DNAbin’, ‘extract_taxonomy.default’, ‘extract_taxonomy.list’, ‘print.taxmap’ were declared in NAMESPACE but not found
> Warning: namespace ‘metacoder’ is not available and has been replaced
> by .GlobalEnv when processing object ‘pr2_ex_data’
> Warning: S3 methods ‘extract_taxonomy.DNAbin’, ‘extract_taxonomy.default’, ‘extract_taxonomy.list’, ‘print.taxmap’ were declared in NAMESPACE but not found
> Warning: namespace ‘metacoder’ is not available and has been replaced
> by .GlobalEnv when processing object ‘rdp_ex_data’
> Warning: S3 methods ‘extract_taxonomy.DNAbin’, ‘extract_taxonomy.default’, ‘extract_taxonomy.list’, ‘print.taxmap’ were declared in NAMESPACE but not found
> Warning: namespace ‘metacoder’ is not available and has been replaced
> by .GlobalEnv when processing object ‘rdp_ex_data’
> Warning: S3 methods ‘extract_taxonomy.DNAbin’, ‘extract_taxonomy.default’, ‘extract_taxonomy.list’, ‘print.taxmap’ were declared in NAMESPACE but not found
> Warning: namespace ‘metacoder’ is not available and has been replaced
> by .GlobalEnv when processing object ‘silva_ex_data’
> Warning: S3 methods ‘extract_taxonomy.DNAbin’, ‘extract_taxonomy.default’, ‘extract_taxonomy.list’, ‘print.taxmap’ were declared in NAMESPACE but not found
> Warning: namespace ‘metacoder’ is not available and has been replaced
> by .GlobalEnv when processing object ‘silva_ex_data’
> Warning: S3 methods ‘extract_taxonomy.DNAbin’, ‘extract_taxonomy.default’, ‘extract_taxonomy.list’, ‘print.taxmap’ were declared in NAMESPACE but not found
> Warning: namespace ‘metacoder’ is not available and has been replaced
> by .GlobalEnv when processing object ‘unite_ex_data_1’
> Warning: S3 methods ‘extract_taxonomy.DNAbin’, ‘extract_taxonomy.default’, ‘extract_taxonomy.list’, ‘print.taxmap’ were declared in NAMESPACE but not found
> Warning: namespace ‘metacoder’ is not available and has been replaced
> by .GlobalEnv when processing object ‘unite_ex_data_1’
> Warning: S3 methods ‘extract_taxonomy.DNAbin’, ‘extract_taxonomy.default’, ‘extract_taxonomy.list’, ‘print.taxmap’ were declared in NAMESPACE but not found
> Warning: namespace ‘metacoder’ is not available and has been replaced
> by .GlobalEnv when processing object ‘unite_ex_data_2’
> Warning: S3 methods ‘extract_taxonomy.DNAbin’, ‘extract_taxonomy.default’, ‘extract_taxonomy.list’, ‘print.taxmap’ were declared in NAMESPACE but not found
> Warning: namespace ‘metacoder’ is not available and has been replaced
> by .GlobalEnv when processing object ‘unite_ex_data_2’
> Warning: S3 methods ‘extract_taxonomy.DNAbin’, ‘extract_taxonomy.default’, ‘extract_taxonomy.list’, ‘print.taxmap’ were declared in NAMESPACE but not found
> Warning: namespace ‘metacoder’ is not available and has been replaced
> by .GlobalEnv when processing object ‘unite_ex_data_3’
> Warning: S3 methods ‘extract_taxonomy.DNAbin’, ‘extract_taxonomy.default’, ‘extract_taxonomy.list’, ‘print.taxmap’ were declared in NAMESPACE but not found
> Warning: namespace ‘metacoder’ is not available and has been replaced
> by .GlobalEnv when processing object ‘unite_ex_data_3’
> ** inst
> ** tests
> ** preparing package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** installing vignettes
> ** testing if installed package can be loaded
> Warning: S3 methods ‘extract_taxonomy.DNAbin’, ‘extract_taxonomy.default’, ‘extract_taxonomy.list’, ‘print.taxmap’ were declared in NAMESPACE but not found
> Error: package or namespace load failed for ‘metacoder’ in namespaceExport(ns, exports):
>  undefined exports: arrange_obs, arrange_taxa, extract_taxonomy, filter_obs, filter_taxa, hierarchies, mutate_obs, mutate_taxa, n_obs, n_obs_1, n_subtaxa, n_subtaxa_1, n_supertaxa, obs, obs_data, obs_data_colnames, parse_taxonomy_table, remove_redundant_names, roots, sample_frac_obs, sample_frac_taxa, sample_n_obs, sample_n_taxa, select_obs, select_taxa, subtaxa, supertaxa, taxmap, taxon_data, taxon_data_colnames, taxonomic_sample, transmute_obs, transmute_taxa
> Error: loading failed
> Execution halted
> ERROR: loading failed
> \* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/metacoder’
> \* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/metacoder’
> Installation failed: Command failed (1)
>

**Comment by zachary-foster** [comment]
Thanks for the report @dougwyu 

The `dev` branch is not used much anymore. `master` is now used as the development branch and tags/CRAN uploads are used to indicate stable releases. I will update the dev branch to master to solve this issue.

**Comment by zachary-foster** [comment]
The dev branch has been deleted. I think in the future I will open up new branches for specific large/experimental changes, but not have a generic "dev" branch. Small changes will be committed directly to master

**Comment by dougwyu** [comment]
i'm unable to install metacoder normally now (i.e. install.packages())

Ah, it was the cran mirror that didn't have it.  the RSTudio mirror has metacoder

**Comment by zachary-foster** [comment]
Odd. I can install normally and with devtools: 

```
> install.packages("metacoder")
Installing package into ‘/home/fosterz/R/x86_64-pc-linux-gnu-library/3.4.1’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/metacoder_0.1.3.tar.gz'
Content type 'application/x-gzip' length 2065240 bytes (2.0 MB)
==================================================
downloaded 2.0 MB

* installing *source* package ‘metacoder’ ...
** package ‘metacoder’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (metacoder)

The downloaded source packages are in
	‘/tmp/RtmpMAlSiC/downloaded_packages’
> devtools::install_github("grunwaldlab/metacoder")
Downloading GitHub repo grunwaldlab/metacoder@master
from URL https://api.github.com/repos/grunwaldlab/metacoder/zipball/master
Installing metacoder
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpMAlSiC/devtools41711c1b7415/grunwaldlab-metacoder-919bee9' --library='/home/fosterz/R/x86_64-pc-linux-gnu-library/3.4.1' --install-tests 

* installing *source* package ‘metacoder’ ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (metacoder)
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.2.1      compiler_3.4.1  R6_2.2.2        tools_3.4.1     withr_1.0.2     curl_2.8.1      memoise_1.1.0   knitr_1.17      git2r_0.19.0   
[10] digest_0.6.12   devtools_1.13.2
```

What error do you get?

**Comment by dougwyu** [comment]
It was the cran mirror that i was using (Cambridge UK).  When i switch to the RStudio global mirror, it works.  i guess there is some propagating that wasn't done.

**Comment by zachary-foster** [comment]
Ok, good to know. Thanks
