### ISSUE TITLE
Importing phylo object

### ISSUE THREAD

**Issue by carlos-arnillas** [grunwaldlab/metacoder#178]
Hello
I have a phylo object and a table linked to it with abundances and I want to import it to the taxmap class. Is there are function to easily do it?
Thanks

Carlos Alberto

**Comment by zachary-foster** [comment]
Hi @carlos-arnillas! A phyloseq object? There is a function in the development version here on github called `parse_phyloseq` that is intended for this, although I cannot guarantee it will work for your data; it is still under development. You can install the development version of metcoder with the following and give it a try: 

```
devtools::install_github("ropensci/taxa")
devtools::install_github("grunwaldlab/metacoder")
```

Give it a try and let me know if it works.

**Comment by carlos-arnillas** [comment]
Hi Zachary
Thanks for you soon reply.
Actually, I meant a phylo object from the package ape

Carlos Alberto

**Comment by zachary-foster** [comment]
No problem! Oh, ok. No, not yet, but most of these parsers are pretty easy to make since the abstracted parsers in the `taxa` package do most of the heavy lifting. Can you send me an example of a phyo object or point me to one in the ape documentation I can use?

**Comment by carlos-arnillas** [comment]
you can easily build a random one by using
rcoal(N)
where N is the number of taxa you want in the phyla. (rcoal generates a
coalescent tree, other functions generate non ultra metric trees)

**Comment by zachary-foster** [comment]
Cool, thanks, I will take a look

**Comment by zachary-foster** [comment]
I think I have a parser working for you. Reinstall the dev version:

```
devtools::install_github("ropensci/taxa")
devtools::install_github("grunwaldlab/metacoder")
```

... and try this:

```r
library(ape)
library(metacoder)
set.seed(2)
parse_phylo(rcoal(100)) %>%
    heat_tree(node_label = tip_label, node_size = n_obs, node_color = n_obs)
```

**Comment by carlos-arnillas** [comment]
Thanks!

**Comment by zachary-foster** [comment]
Did this work for your data? Can I close this? Thanks!

**Comment by carlos-arnillas** [comment]
Hi Zachary
Yes... I managed to import my data. Thanks!

Carlos Alberto

**Comment by zachary-foster** [comment]
Cool, Thanks!
