### ISSUE TITLE
Taxon ids in various data tables do not match up.

### ISSUE THREAD

**Issue by grabear** [grunwaldlab/metacoder#188]
I have some data from the QIIME FASTQ Paired End [Nephele Pipeline ](https://nephele.niaid.nih.gov/#form?id=QIIME%20FASTQ%20Paired%20End).  It's qiime data that uses taxonomy strings from the SILVA database.  Anyways, I was able to coerce this data into a phyloseq object, and then into a taxmap object via the instructions found [here](https://github.com/grunwaldlab/metacoder/blob/72e77a04b34c7dfa425f897512f126330d46d887/scratch/issue_141--phyloseq_converter.Rmd) (labeled **Even newer way**).  Below I've added my scripting.

```r
library(modes)
library(phyloseq)
library(ggtree)
library(ggplot2)
library(dplyr)
library(metacoder)
library(taxa)
library(modes)
library(diptest)
setwd("~/Nephele_Data/SILVA_Output/RData")

############################################################################
# Custom Phyloseq function (dev) - blessed by @joey711
parse_taxonomy_silva <- function(char.vec){
  # Use default to assign names to elements in case problem with greengenes prefix
  char.vec = parse_taxonomy_default(char.vec)
  # Check for unassigned taxa
  if (char.vec["Rank1"] == "Unassigned") {
    char.vec <- c(Rank1="D_0__Unassigned", Rank2="D_1__Unassigned", Rank3="D_2__Unassigned", Rank4="D_3__Unassigned",
                  Rank5="D_4__Unassigned", Rank6="D_5__Unassigned", Rank7="D_6__Unassigned")
  }
  # Define the meaning of each prefix according to GreenGenes taxonomy
  Tranks = c(D_0="Kingdom", D_1="Phylum", D_2="Class", D_3="Order", D_4="Family", D_5="Genus", D_6="Species")
  # Check for prefix using regexp, warn if there were none. trim indices, ti
  ti = grep("[[:alpha:]]\\_[[:digit:]]{1}\\_\\_", char.vec)
  if( length(ti) == 0L ){
    warning(
      "No silva prefixes were found. \n",
      "Consider using parse_taxonomy_delfault() instead if true for all OTUs. \n",
      "Dummy ranks may be included among taxonomic ranks now."
    )
    # Will want to return without further modifying char.vec
    taxvec = char.vec
    # Replace names of taxvec according to prefix, if any present...
  } else {
    # Format character vectors for Ambiguous taxa
    if( length(ti) < 7 ){
      for (key in names(char.vec)) {
        if ( char.vec[key] == "Ambiguous_taxa" ) {
          tax_no <- (as.numeric(substr(key, 5, 5)) - 1)
          char.vec[key] = sprintf("D_%s__Ambiguous_taxa", tax_no)
        }
      }
      # Reset the trimmed indicies if Ambiguous taxa
      ti = grep("[[:alpha:]]\\_[[:digit:]]{1}\\_\\_", char.vec)
    }
    # Remove prefix using sub-"" regexp, call result taxvec
    taxvec = gsub("[[:alpha:]]\\_[[:digit:]]{1}\\_\\_", "", char.vec)
    # Define the ranks that will be replaced
    repranks = Tranks[substr(char.vec[ti], 1, 3)]
    # Replace, being sure to avoid prefixes notK present in Tranks
    names(taxvec)[ti[!is.na(repranks)]] = repranks[!is.na(repranks)]
  }
  return(taxvec)
}

############################################################################
# A new function for metacoder::compare_treatments method
new_comparison <- function(abund_1, abund_2) {
  log_ratio <- log2(median(abund_1) / median(abund_2))
  if (is.nan(log_ratio)) {
    log_ratio <- 0
  }
  if (is.infinite(log_ratio)) {
    log_ratio <- 0
  }
  
  list(log2_median_ratio = log_ratio,
       median_diff = median(abund_1) - median(abund_2),
       mean_diff = mean(abund_1) - mean(abund_2),
       wilcox_p_value = wilcox.test(abund_1, abund_2)$p.value,
       hartigan_dip_treat1 = dip.test(abund_1)$p.value,
       hartigan_dip_treat2 = dip.test(abund_2)$p.value,
       bimodality_coeff_treat1 = bimodality_coefficient(abund_1),
       bimodality_coeff_treat2 = bimodality_coefficient(abund_2))
}
# ############################################################################
# ,
# bimodality_amp_abund1 = bimodality_amplitude(abund_1, FALSE),
# bimodality_amp_abund2 = bimodality_amplitude(abund_2, FALSE)
b_file = "../Decompressed_Data/PipelineResults_N6F36627L6NS/nephele_outputs/OTU_table.biom"
t_file = "../Decompressed_Data/PipelineResults_N6F36627L6NS/nephele_outputs/tree.tre"
sd_file = "../Decompressed_Data/PipelineResults_N6F36627L6NS/nephele_outputs/data.txt"

# Load the biom file and the Full tree file into a phyloseq object
biom <- import_biom(BIOMfilename = b_file, treefilename = t_file, parseFunction = parse_taxonomy_silva)
# Write to a tree file that subsets our data
biom_tree <- phy_tree(biom)
write.tree(biom_tree, "OTU_table.tre")

#Extract metadata from the phyloseq object:
biom_md <- import_qiime_sample_data(sd_file)

# Create a phyloseq object with all of our data
master_biom <- merge_phyloseq(biom, biom_md)

########################################################################################################
########################################################################################################
# MetacodeR Workflow
########################################################################################################
########################################################################################################

# Convert Phyloseq objects to Metacoder objects
master_metacoder <- parse_phyloseq(master_biom)
# Convert column names so that the numeric sample ids won't cause errors
names(master_metacoder$data$otu_table)[names(master_metacoder$data$otu_table) %in% master_metacoder$data$sam_data$sample_ids]<- paste("Sample", names(master_metacoder$data$otu_table)[names(master_metacoder$data$otu_table) %in% master_metacoder$data$sam_data$sample_ids], sep = "_")
master_metacoder$data$sam_data$sample_ids <- paste("Sample", master_metacoder$data$sam_data$sample_ids, sep = "_")
master_metacoder$data$sam_data$X.SampleID <- paste("Sample", master_metacoder$data$sam_data$X.SampleID, sep = "_")

# Calculate a proportionate abundance value for each sample
master_metacoder$data$otu_table <- calc_obs_props(master_metacoder, dataset = "otu_table", cols = master_metacoder$data$sam_data$sample_ids)
# Calculate the proportionate abundace per-taxon value for each sample
master_metacoder$data$tax_table <- calc_taxon_abund(master_metacoder, dataset = "otu_table", cols = master_metacoder$data$sam_data$sample_ids)
# Calculate the differences between Stress vs Control
master_metacoder$data$diff_table <- compare_treatments(master_metacoder, dataset = "tax_table", cols = master_metacoder$data$sam_data$sample_ids, groups = master_metacoder$data$sam_data$TreatmentGroup, func = new_comparison)
```

Comparing the taxon ids of the diff table show that there are ~200 ids that don't exist within the tax_data table.  What can I do about this?  Is this normal?  I need tax_data info for labeling some of my data in scatter plots.
```r
> master_metacoder$data$diff_table %>% filter(!(taxon_id %in% master_metacoder$data$tax_data$taxon_id))
# A tibble: 201 x 13
   taxon_id treatment_1 treatment_2 log2_median_ratio   median_diff     mean_diff wilcox_p_value
      <chr>       <chr>       <chr>             <dbl>         <dbl>         <dbl>          <dbl>
 1       ab    Stressed     Control        -0.2000881 -0.0018537976 -0.0018019995   1.953602e-01
 2       ad    Stressed     Control         3.4778077  0.0001010186  0.0007438088   2.386317e-02
 3       ae    Stressed     Control        -0.2000881 -0.0018537976 -0.0018019995   1.953602e-01
 4       ag    Stressed     Control        -0.5416257 -0.0045368542 -0.0045522507   2.191329e-01
 5       ah    Stressed     Control         0.8041503  0.0073317478  0.0108519237   1.411135e-01
 6       ai    Stressed     Control        -2.0742126 -0.0007415206  0.0005458533   8.518898e-03
 7       aj    Stressed     Control        -0.2603768 -0.0954516613 -0.1085451483   1.594025e-03
 8       ak    Stressed     Control         1.0667023  0.0003654691  0.0014278402   7.283499e-02
 9       al    Stressed     Control        -2.6525393 -0.0008804932 -0.0009525155   1.241754e-06
10       an    Stressed     Control         1.2054984  0.0004406935  0.0007639738   1.519523e-01
# ... with 191 more rows, and 6 more variables: hartigan_dip_treat1 <dbl>, hartigan_dip_treat2 <dbl>,
#   bimodality_coeff_treat1 <dbl>, bimodality_coeff_treat2 <dbl>, bimodal_suspect_treat1 <lgl>,
#   bimodal_suspect_treat2 <lgl>
```

**Comment by zachary-foster** [comment]
Hello @grabear, thanks for the report!

> Comparing the taxon ids of the diff table show that there are ~200 ids that don't exist within the tax_data table. 

I cant say for sure without replicating your example (I would need your input files for that), but I think I know what is going on. You checked for IDs in `tax_data`, which is the result of parsing what I assume are OTUs or some other thing with a taxonomic assignment. Those will usually be at the "tips"/"leaves" of the taxonomy, so that table will probably not contain things assigned to "Bacteria" or "Protobacteria" for example, but those are still taxa with IDs in the `taxmap` object, so they will be given values when you calculate the per-taxon characteristics. For example, I bet "ab" is "Bacteria". 

I am guessing that if you run: 

```r
master_metacoder$data$diff_table %>% filter(!(taxon_id %in% master_metacoder$data$tax_table$taxon_id))
```

You will get no results. (note the "tax_table" instead of "tax_data"). 

> What can I do about this? Is this normal?

Without running it myself, I think this is normal. 

> I need tax_data info for labeling some of my data in scatter plots.

Most likely, you will not have rows in "tax_data" that correspond to every taxon. E.g, you probably don't have any OTUs assigned to "Bacteria" explicitly, but rather to subtaxa of Bacteria. The `compare_treatments` command was given the result of `calc_taxon_abund`, which returns one row per taxon, not one row per OTU, so every taxon will be compared to every other taxon, not OTU to OTU. Therefore if you want to combine information from "tax_data" and "diff_table" you can do something like:

* dplry::left_join(master_metacoder$data$diff_table, master_metacoder$data$tax_data, by = "taxon_id") 

This will produce `NA`s for the taxa like "Bacteria" that dont have information from your input data.

Make sense? Let me know if you have questions

**Comment by grabear** [comment]
> I am guessing that if you run:
> ```r
> master_metacoder$data$diff_table %>% filter(!(taxon_id %in% master_metacoder$data$tax_table$taxon_id))
> ```
> You will get no results. (note the "tax_table" instead of "tax_data").

That's correct.

> Make sense? Let me know if you have questions

Everything is making sense.  I understand the stuff about `calc_taxon_abund` and how it creates the abundance data per taxon (and not OTU).  And I get why it's not in the tax_data table.

> ```r
> left_join(master_metacoder$data$diff_table, master_metacoder$data$tax_data, by = "taxon_id")
> ```

I did this part and there were ton's of NA's.  I was mostly curious about how to coerce the data to fill in the blanks for some of these.  I know this is a taxmap, and I've read the documentation there too.

My problem is that there is unassigned taxon_rank information for taxon_name data in the taxmap.  If this is normal, then that's fine.  But I still need a way to access it (via ropensci/taxa, joey711/phyloseq, grunwaldlab/metacoder, or proprietary code).  If it's not normal then, I need to take a closer look at my data or workflow.  

Below I've looked deeper into the original "id's that don't exist".
```r
# The "missing diff table" from the original comment
> nt
# A tibble: 201 x 13
   taxon_id treatment_1 treatment_2 log2_median_ratio   median_diff     mean_diff wilcox_p_value
      <chr>       <chr>       <chr>             <dbl>         <dbl>         <dbl>          <dbl>
 1       ab    Stressed     Control        -0.2000881 -0.0018537976 -0.0018019995   1.953602e-01
 2       ad    Stressed     Control         3.4778077  0.0001010186  0.0007438088   2.386317e-02
 3       ae    Stressed     Control        -0.2000881 -0.0018537976 -0.0018019995   1.953602e-01
 4       ag    Stressed     Control        -0.5416257 -0.0045368542 -0.0045522507   2.191329e-01
 5       ah    Stressed     Control         0.8041503  0.0073317478  0.0108519237   1.411135e-01
 6       ai    Stressed     Control        -2.0742126 -0.0007415206  0.0005458533   8.518898e-03
 7       aj    Stressed     Control        -0.2603768 -0.0954516613 -0.1085451483   1.594025e-03
 8       ak    Stressed     Control         1.0667023  0.0003654691  0.0014278402   7.283499e-02
 9       al    Stressed     Control        -2.6525393 -0.0008804932 -0.0009525155   1.241754e-06
10       an    Stressed     Control         1.2054984  0.0004406935  0.0007639738   1.519523e-01
# ... with 191 more rows, and 6 more variables: hartigan_dip_treat1 <dbl>, hartigan_dip_treat2 <dbl>,
#   bimodality_coeff_treat1 <dbl>, bimodality_coeff_treat2 <dbl>, bimodal_suspect_treat1 <lgl>,
#   bimodal_suspect_treat2 <lgl>
```

The taxon_names are available.  I knew they must be, because I've produced super awesome heat-trees already with the same data.

```r
> master_metacoder$supertaxa(subset = nt$taxon_id, value = "taxon_names")
...
# skip a few hundred lines
# Everythin is assigned a name
$jo
                 eo                  cr                  bm                  ao                  ac 
"Elusimicrobiaceae"  "Elusimicrobiales"     "Elusimicrobia"     "Elusimicrobia"          "Bacteria" 

$jp
               de                bv                aw                af                ac 
"Lachnospiraceae"   "Clostridiales"      "Clostridia"      "Firmicutes"        "Bacteria" 

$jr
              dy               ch               be               aj               ac 
"Prevotellaceae"  "Bacteroidales"    "Bacteroidia"  "Bacteroidetes"       "Bacteria" 

$js
                   ds                    cd                    ba                    ag                    ac 
 "Enterobacteriaceae"   "Enterobacteriales" "Gammaproteobacteria"      "Proteobacteria"            "Bacteria" 
```

However, the **taxon_ranks** are not availabe.

```r
> master_metacoder$supertaxa(subset = nt$taxon_id, value = "taxon_ranks")
...
# skip a few hundred lines
# Everything is NA for taxon rank
$dn
by az ag ac 
NA NA NA NA 

$do
bz az ag ac 
NA NA NA NA 

$dp
ca az ag ac 
NA NA NA NA 

$dq
cb ba ag ac 
NA NA NA NA 

$ds
cd ba ag ac 
NA NA NA NA 

$dt
ce bb ah ac 
NA NA NA NA 

$dv
cf bc ag ac 
NA NA NA NA 

$dw
cg bd ai ac 
NA NA NA NA 

$dx
ch be aj ac 
NA NA NA NA 

```

If you need to see my data, then I can add you to my private repository for easy git access.

Cheers @zachary-foster!  And thanks for the awesome package and for the insight.

**Comment by zachary-foster** [comment]
Thanks for the kind words! 

> My problem is that there is unassigned taxon_rank information for taxon_name data in the taxmap. 

I see what you mean now. So the `taxon_names` and `taxon_ranks` are functions that pretend to be column names and are associated with taxa 1:1. These functions are run whenever they are referenced in a function like `supetaxa` or `filter_taxa`. You can see all of them by running `master_metacoder$all_names(tables = F, others = F)`. The rank and name information comes from the `Taxon` objects in `master_metacoder$taxa`. 

The taxon names are pretty much always there, but the rank information is optional in the `Taxon` objects. Name or rank information can also appear in the tables, but that is not where `taxon_names` and `taxon_ranks` look.  I think the way your data was parsed, the rank information was not included in `Taxon` objects, so `taxon_ranks` cant find it. Thats probably an oversight on my part when making the `parse_phyloseq` function. I will look into that (#189). 

As for getting the `taxon_name` info: 

`master_metacoder$taxon_names()`

And to get it into one of your tables:

`master_metacoder$data$my_table$tax_name <- master_metacoder$taxon_names()[master_metacoder$data$my_table$taxon_ids]`

I will get back to you about that rank info. 

> If you need to see my data, then I can add you to my private repository for easy git access.

Thanks! That might be helpful if any other questions come up or I have trouble get the rank info included

**Comment by zachary-foster** [comment]
Hi @grabear, I might have the rank info working now. Try reinstalling the taxa and metacoder:

```
devtools::install_github("ropensci/taxa")
devtools::install_github("grunwaldlab/metacoder")
```

You should now be able to get the taxon rank information like so: 

master_metacoder$taxon_ranks()

And to get it into one of your tables:

master_metacoder$data$my_table$tax_rank <- master_metacoder$taxon_ranks()[master_metacoder$data$my_table$taxon_ids]

Is that what you needed?

**Comment by grabear** [comment]
> I see what you mean now. So the taxon_names and taxon_ranks are functions that pretend to be column names and are associated with taxa 1:1. These functions are run whenever they are referenced in a function like supetaxa or filter_taxa. You can see all of them by running master_metacoder$all_names(tables = F, others = F). The rank and name information comes from the Taxon objects in master_metacoder$taxa.

@zachary-foster Yes this is what I've been doing to understand my data better.  I read a ton of the taxa documentation and a ton of the metacoder documentation.  It's very well done.  Thanks for putting in all the work!  I might make a PR when I'm finished to help out with the docs.

> Hi @grabear, I might have the rank info working now. Try reinstalling the taxa and metacoder:
> 
> devtools::install_github("ropensci/taxa")
> devtools::install_github("grunwaldlab/metacoder")
> You should now be able to get the taxon rank information like so:
> 
> master_metacoder$taxon_ranks()
> 
> And to get it into one of your tables:
> 
> master_metacoder$data$my_table$tax_rank <- master_metacoder$taxon_ranks()[master_metacoder$data$my_table$taxon_ids]
> 
> Is that what you needed?

Thank you so much for getting this in over the holidays.  That works perfectly.  This is what's available to me now:

```r
> master_metacoder$taxa$ac
<Taxon>
  name: Bacteria
  rank: Kingdom
  id: none
  authority: none
```

My next goal is to attempt to figure out how to easily replace the taxon ids with equivalent NCBI taxon IDs.  However, this isn't fully necessary.  So anyways, this works very well for my workflow.  I really appreciate your involvement and help on this issue!

**Comment by zachary-foster** [comment]
>  Thanks for putting in all the work! I might make a PR when I'm finished to help out with the docs.

Thank you! We always appreciate any contributions!

> My next goal is to attempt to figure out how to easily replace the taxon ids with equivalent NCBI taxon IDs. 

There is a function to make replacing the IDs easier in `taxa`. See `?taxa::replace_taxon_ids`. If the NCBI ids are already in your dataset, then that should be easy. If not, you can use some functions in `taxize` to look up the IDs. However, NCBI's servers are slow, so that might take a while if you have a diverse data set.
