### ISSUE TITLE
(Phyloseq workflow) OTU labels are inaccessible.

### ISSUE THREAD

**Issue by grabear** [grunwaldlab/metacoder#219]
I'm currently converting a phyloseq object into a metacoder object.  In my use of metacoder, i wondered where the OTU labels had gone.  They are only visible in my data via the phylogenetic tree (if you include one in your data).

I was wondering if there was a way to import a phyloseq object while preserving the OTU labels (such as _EU774211.1.1284, New.ReferenceOTU1302, New.CleanUp.ReferenceOTU194, etc..._ in the taxmap object.  
Potential solutions:
* Theoretically it could be used as authority data in the [taxon-class](https://github.com/ropensci/taxa#the-taxon-class).  
* Regardless, I think this particular data should be included next to the taxon_id of every data table in the metacoder$data object.  The column name could be OTU, with an $all_names style function like similar to taxon_ids(), but otu_ids().
* The taxon class could also be manipulated to add hash/dictionary/key:value like data.

**Comment by grabear** [comment]
This would mostly help keep the data uniform across phyloseq/metacoder and the original data source.

**Comment by grabear** [comment]
**This has been taken care of in Issue #220 **
> This brings up another point that needs to be clarified (unless I've missed the documentation).
> The taxon_ids that are present in the otu_table/tax_data tables are different, but related to the taxon_ids in the tax_table/diff_tables created by coercing the phyloseq object into a taxmap object as shown [here](https://github.com/grunwaldlab/metacoder/blob/master/scratch/issue_141--phyloseq_converter.Rmd).
> 
> While the different taxon_ids are obviously just part of the taxmap heirarchy, the confusion could be remedied by including the OTU label for taxon_ids that are legitimately identified/annotated organisms.  While intermediate taxon_ids that are used to identify/accumulate data for each of the intermediate taxonomic ranks, are left without this OTU label.
> 
> The intermediate taxon_ids could also be given a group OTU label that gives access to the list of OTU labels that are included in that taxonomy.

**Comment by zachary-foster** [comment]
Hi @grabear, for my test data, it seems the OTU ID is included in the "otu_table" table, right after the taxon_id column

```
<Taxmap>
  2692 taxa: aab. Archaea, aac. Bacteria, aad. Crenarchaeota ... hkg. Thermanaerovibrioacidaminovorans, hkk. Jonquetellaanthropi
  2692 edges: NA->aab, NA->aac, aab->aad, aab->aae, aac->aaf, aac->aag ... dyy->hjq, dzb->hju, dzc->hjv, dzf->hjy, dzn->hkg, dzr->hkk
  4 data sets:
    otu_table:
      # A tibble: 19,216 x 28
        taxon_id otu_id   CL3   CC1   SV1 M31Fcsw M11Fcsw M31Plmr M11Plmr F21Plmr M31Tong M11Tong LMEpi24M SLEpi20M AQC1cm AQC4cm AQC7cm
        <chr>    <chr>  <dbl> <dbl> <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>    <dbl>    <dbl>  <dbl>  <dbl>  <dbl>
      1 acs      549322     0     0     0       0       0       0    0          0       0       0        0     1.00   27.0 100    130   
      2 acs      522457     0     0     0       0       0       0    0          0       0       0        0     0       0     2.00   6.00
      3 dzw      951        0     0     0       0       0       0    1.00       0       0       0        0     0       0     0      0   
      # ... with 1.921e+04 more rows, and 11 more variables: NP2 <dbl>, NP3 <dbl>, NP5 <dbl>, TRRsed1 <dbl>, TRRsed2 <dbl>,
      #   TRRsed3 <dbl>, TS28 <dbl>, TS29 <dbl>, Even1 <dbl>, Even2 <dbl>, Even3 <dbl>
```

Although it is not in any of the other tables. In your object, are you not seeing this 'otu_id' column? It is derived from the row names in the `@otu_table` in the input object. 

> Theoretically it could be used as authority data in the taxon-class.

I think a column would work better since OTUs are not per-taxon info, but per-observation info.

> Regardless, I think this particular data should be included next to the taxon_id of every data table in the metacoder$data object. The column name could be OTU, with an $all_names style function like similar to taxon_ids(), but otu_ids().

I could easily add it to the taxonomy table if you think that would be convenient for users. Adding it as a standard column would make it accessible via the `all_names` and NSE, however having multiple tables sharing a column name (besides taxon_id) makes it unclear which the user is referring to when using NSE. I am guessing that this is the reason I did not included it in the taxonomy table (which is not really needed since all the taxonomic information is captured by the taxon ID column in the "otu_table").

**Comment by grabear** [comment]
There is no otu column in any of my tables.  I will gather my thoughts on this tomorrow though after I do some exploratory work with my phyloseq object and it's conversion to metacoder's taxmap object.

**Comment by grabear** [comment]
I'm about to look into this.  Was this particular test data for phyloseq objects? @zachary-foster

**Comment by grabear** [comment]
This was resolved.  Sorry for the confusion.  I updated my code after [parsing the phyloseq](https://github.com/grunwaldlab/metacoder/blob/master/scratch/issue_141--phyloseq_converter.Rmd) object to include **other_cols = TRUE** when using the _calculation_ functions provided in metacoder.  #221

**Comment by grabear** [comment]
Adding it to the taxonomy table would be great! @zachary-foster
