### ISSUE TITLE
Add groups option to calc_obs_props

### ISSUE THREAD

**Issue by zachary-foster** [grunwaldlab/metacoder#224]
This would be useful for get proportions for treatments

**Comment by amusheg** [comment]
I was just coming here to ask about something like this. I can imagine doing two different things: 1) setting color or size of a node to the proportion of reads across all samples in a treatment that correspond to a particular taxon, similar to when all samples in a treatment are pooled to make a stacked bar chart or 2) setting color or size of a node to the median proportion of a sample in a given treatment that a taxon comprises. That is, it'd be great to be able to say "Larger nodes represent taxa with a greater relative abundance across all samples in treatment X" or "Larger nodes represent taxa with a greater median relative abundance in samples in treatment X." I hope that makes sense; I'm not completely comfortable with the vocabulary of metacoder yet. (Though I can already see how useful and powerful it is!)
