### ISSUE TITLE
n_obs meaning

### ISSUE THREAD

**Issue by amusheg** [grunwaldlab/metacoder#226]
Hello! I'm full of questions. Could you help me understand what the n_obs parameter refers to?

The documentation says that n_obs refers to

> Count observations for each taxon in a taxmap() object. This includes observations for the specific taxon and its subtaxa.

My interpretation of this is that observations=individuals or reads. So if n_obs for a taxon is 3, that means individuals of that taxon were observed 3 times in a data set.

But the example demonstration, n_obs always seems to refer to the **number of OTUs in a given taxon.** So if n_obs for a taxon is 3, that means there were 3 different OTUs in that taxon, but you don't know how many individuals/reads of that taxon were observed.

Does n_obs mean different things in different contexts? If so, how do you specify the context?

Thank you again!

**Comment by zachary-foster** [comment]
`n_obs` is a function from the `taxa` package. I added some extra description, so now it says:


> Count observations for each taxon in a data set in a taxmap() object. This includes observations for the specific taxon and the observations of its subtaxa. "Observations" in this sense are the items (for list/vectors) or rows (for tables) in a dataset. By default, observations in the first data set in the taxmap() object is used. For example, if the data set is a table, then a value of 3 for a taxon means that their are 3 rows in that table assigned to that taxon or one of its subtaxa.

Does that make more sense? 

>But the example demonstration, n_obs always seems to refer to the number of OTUs in a given taxon.

It refers to the number of rows/items in a data set classified by a taxonomy. Usually that is OTUs, but what it is depends on what the table contains.

> Does n_obs mean different things in different contexts? If so, how do you specify the context?

It depends on the data set used. The first by default. When using the `n_obs` in a `metacoder` function (`heat_tree`), the first table is used, unless you call it like so: `n_obs(ex_taxmap, "my_data_set")`.

`n_obs` is related to the `obs` function. Perhaps this example will help: 

```
> obs(ex_taxmap, "info", value = "taxon_names")
$b
         m          n          o          p 
  "tigris"    "catus" "typhlops"  "sapiens" 

$c
             q              r 
"lycopersicum"    "tuberosum" 

$d
       m        n 
"tigris"  "catus" 

$e
         o 
"typhlops" 

$f
        p 
"sapiens" 

$g
             q              r 
"lycopersicum"    "tuberosum" 

$h
       m 
"tigris" 

$i
      n 
"catus" 

$j
         o 
"typhlops" 

$k
        p 
"sapiens" 

$l
             q              r 
"lycopersicum"    "tuberosum" 

$m
       m 
"tigris" 

$n
      n 
"catus" 

$o
         o 
"typhlops" 

$p
        p 
"sapiens" 

$q
             q 
"lycopersicum" 

$r
          r 
"tuberosum" 

> sapply(obs(ex_taxmap, "info", value = "taxon_names"), length) == n_obs(ex_taxmap, "info")
   b    c    d    e    f    g    h    i    j    k    l    m    n    o    p    q    r 
TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
```

**Comment by amusheg** [comment]
Thank you! The extra bit of explanation in the documentation is helpful.

**Comment by zachary-foster** [comment]
Nice, can we close this issue then?
