### ISSUE TITLE
Error using use_total in zero_low_counts command

### ISSUE THREAD

**Issue by jarrodscott** [grunwaldlab/metacoder#227]
Hi @zachary-foster !

I am encountering an error when using `use_total` in ` zero_low_counts`. I get this error using my data as well the `hmp` data

here is the code (from your tutorial)

`print(hmp_otus)`
`print(hmp_samples)`
`obj2 <- parse_tax_data(hmp_otus, class_cols = "lineage", class_sep = ";",
                      class_key = c(tax_rank = "info", tax_name = "taxon_name"),
                      class_regex = "^(.+)__(.+)$")`
`print(obj2)`
`obj2$data$tax_data <- zero_low_counts(obj2, "tax_data", use_total = TRUE, min_count = 5)`

and I get the following error:

`Error in if (all(!is_greater_than_max)) { : 
  missing value where TRUE/FALSE needed`

The error persist no matter what value I use for `min_counts` when `use_total = TRUE`. If I use the default setting `use_total = FALSE` I can process the dataset completely following the tutorial. 

Using:
`R version 3.3.3 (2017-03-06) -- "Another Canoe"`
`metacoder verison 0.2.0.9011`
`OSX 10.10.5`

**Comment by zachary-foster** [comment]
Thanks for the report!

I think I have it fixed. Try to install the dev version and see if it goes away:

```
devtools::install_github("ropensci/taxa")
devtools::install_github("grunwaldlab/metacoder")
```

**Comment by jarrodscott** [comment]
Thanks! I will try later this evening when in computer and let you know :)

**Comment by jarrodscott** [comment]
that works! Thanks @zachary-foster

**Comment by zachary-foster** [comment]
Cool thanks!
