### ISSUE TITLE
Phyloseq parser error

### ISSUE THREAD

**Issue by amusheg** [grunwaldlab/metacoder#228]
Hello,
I installed version 0.2.0.9012 of metacoder because I'd like to use the calc_group_medians function. However, this version seems to have a problem with the phyloseq parser. 

```
devtools::install_github("grunwaldlab/taxa")
devtools::install_github("grunwaldlab/metacoder")
library(metacoder)
obj<-parse_phyloseq(adata)
```
```
Error: 'parse_tax_data' is not an exported object from 'namespace:taxa'
```
Please let me know if you need more details.

Thank you!

**Comment by zachary-foster** [comment]
Hello @amusheg, it looks like you are using the wrong `taxa` repo. It should be "ropensci", not "grunwaldlab". The one on grunwaldlab is probably an old fork.

```r
devtools::install_github("ropensci/taxa")
devtools::install_github("grunwaldlab/metacoder")
library(metacoder)
obj<-parse_phyloseq(adata)
```

**Comment by amusheg** [comment]
That works. Thank you!
