### ISSUE TITLE
Parsing Error: input(s) could not be matched by the regex supplied following example in README.md

### ISSUE THREAD

**Issue by akiledal** [grunwaldlab/metacoder#232]
Processing data very similar to the example in the README.md, I get this error message:

> Error: The following 3 of 7 input(s) could not be matched by the regex supplied: f__, g__, s__

This was working for me before the recent updates, and now with the same code I get this error. Am I missing something or did the update possibly break parsing taxonomy information in this format? Using class_regex = "^(.+)__(.+)$"

Example taxa:
>k__Bacteria;   p__Acidobacteria; c__Acidobacteriia; o__Acidobacteriales; f__Koribacteraceae;   g__; s__
>k__Bacteria; p__Acidobacteria; c__DA052;   o__Ellin6513; f__; g__; s__

**Comment by zachary-foster** [comment]
Hello @akiledal, since the update, the function does a bit more checking of inputs and is more picky. Before, it would just call those taxa `NA` I think. 

Its because the regex does not match things like " f__". Changing the regex to `"^(.+)__(.*)$"` might work. the `+` means "one or more" and the `*` means "zero or more", so the using `*` instead should allow for blank taxon names.

```r
> raw_data = c("k__Bacteria; p__Acidobacteria; c__Acidobacteriia; o__Acidobacteriales; f__Koribacteraceae; g__; s__",
+              "k__Bacteria; p__Acidobacteria; c__DA052; o__Ellin6513; f__; g__; s__")
> obj <- parse_tax_data(raw_data,
+                       class_regex =  "^(.+)__(.*)$",
+                       class_key = c(my_rank = "taxon_rank", my_name = "taxon_name"))
> obj
<Taxmap>
  12 taxa: b. Bacteria, c. Acidobacteria, d. Acidobacteriia, e. DA052, f. Acidobacteriales ... i. , j. , k. , l. , m. 
  12 edges: NA->b, b->c, c->d, c->e, d->f, e->g, f->h, g->i, h->j, i->k, j->l, k->m
  2 data sets:
    tax_data: a named vector of 'character' with 2 items
       l. k__Bacteria; p__[truncated] ... m. k__Bacteria; p__[truncated]
    class_data:
      # A tibble: 14 x 5
        taxon_id input_index my_rank my_name        regex_match      
      * <chr>          <int> <chr>   <chr>          <chr>            
      1 b                  1 k       Bacteria       k__Bacteria      
      2 c                  1 p       Acidobacteria  p__Acidobacteria 
      3 d                  1 c       Acidobacteriia c__Acidobacteriia
      # ... with 11 more rows
  0 functions:
> taxon_ranks(obj)
  b   c   d   e   f   g   h   i   j   k   l   m 
"k" "p" "c" "c" "o" "o" "f" "f" "g" "g" "s" "s" 
> taxon_names(obj)
                 b                  c                  d                  e                  f                  g                  h 
        "Bacteria"    "Acidobacteria"   "Acidobacteriia"            "DA052" "Acidobacteriales"        "Ellin6513"  "Koribacteraceae" 
                 i                  j                  k                  l                  m 
                ""                 ""                 ""                 ""                 "" 
```

**Comment by akiledal** [comment]
Works wonderfully again with your suggested regex. Thanks for this package and your help here!

**Comment by zachary-foster** [comment]
No problem! Im glad it worked out

**Comment by taylorreiter** [comment]
I receive a similar error when using the function `parse_silva_fasta()`, however I do not see an argument to change the regex. Is there a work around for this?

```
Error: The following 1 of 10 input(s) could not be matched by the regex supplied:
   Saccharomyces cf. cerevisiae/paradoxus
```

**Comment by zachary-foster** [comment]
Are you using the unmodified SILVA database or a subset of it as input? If so, thats a bug. Otherwise, it would probably be best to use `parse_tax_data`.
