### ISSUE TITLE
A warning message from 'parse_mothur_tax_summary'

### ISSUE THREAD

**Issue by ilnamkang** [grunwaldlab/metacoder#236]
Hi,

I get a warning message when I run 'parse_mothur_tax_summary' for my taxonomy summary file from Mothur. Below is my command and messages copied from the console. I used Mothur ver. 1.40.3 and classified sequences using Silva132 reference files downloaded from the Mothur homepage.

What should I do to avoid this warning?

>parse_mothur_tax_summary(file = "sample.tax.summary")
<Taxmap>
  1673 taxa: aab. Root, aac. Bacteria ... cmi. Roseibacillus, cmj. WPS-2_ge
  1673 edges: NA->aab, aab->aac, aac->aad, aac->aae ... bcy->cmg, bcz->cmh, bcz->cmi, bda->cmj
  1 data sets:
    tax_data:
      # A tibble: 1,673 x 16
        taxon_id taxlevel rankID taxon    daughterlevels total  TAS1 TAS10  TAS2  TAS3  TAS4  TAS5
        <chr>       <int> <chr>  <chr>             <int> <int> <int> <int> <int> <int> <int> <int>
      1 aab             0 0      Root                  1 61163  4699  6993  4105  5969  7104  3154
      2 aac             1 0.1    Bacteria             31 61163  4699  6993  4105  5969  7104  3154
      3 aad             2 0.1.1  Acidoba~              8   890     4     4     0     3    14   639
      # ... with 1,670 more rows, and 4 more variables: TAS6 <int>, TAS7 <int>, TAS8 <int>,
      #   TAS9 <int>
  0 functions:
Warning message:
Naming table columns/vectors/lists the same name as functions can sometimes interfere with non-standard evaluation. The following data shares names with functions:
 data$tax_data$taxon

**Comment by zachary-foster** [comment]
Hello @ilnamkang, thanks for the report. You don't need to worry about that warning. At one point we had a problem with non-standard evaluation confusing external variables with column names, but I think that is fixed now. We will be removing removing that warning from the next release.

**Comment by ilnamkang** [comment]
Oh, I see. Thanks for your reply.
