### ISSUE TITLE
Is there a way to turn off node labels when they are grey

### ISSUE THREAD

**Issue by terrimporter** [grunwaldlab/metacoder#251]
Is there a way to turn off node labels when the n_obs = 0?

I've checked around for an answer but no luck, can you re-direct me or advise?

**Comment by zachary-foster** [comment]
Hello @terrimporter, yea, if you set a node label to `""` or `NA` it will not show. One way to do this is something like:

```r
heat_tree(..., node_label = ifelse(n_obs == 0, NA, taxon_names), ...)
```

Make sense?

**Comment by terrimporter** [comment]
That¹s fantastic, thank you so much.

By the way, I was a bit hesitant to try your package at first (even though
the graphics looked great) but I was pleasantly surprised that it was so
easy to use.  The example on your website pretty much covered what I needed
to know.  I¹d totally recommend it.

**Comment by zachary-foster** [comment]
Thank you!
