### ISSUE TITLE
Errors when parse phyloseq object

### ISSUE THREAD

**Issue by ireceptor** [grunwaldlab/metacoder#259]
Hi,

When I tried to use parse_phyloseq to import my data, I got the error below:

> Error: The following taxon IDs do not exist:
 NA

and the data can't be imported to metacoder. I got the same error when I tried with the example data in phyloseq:
> x <- parse_phyloseq(GlobalPatterns)
Error: The following taxon IDs do not exist:
 NA
In addition: Warning message:
The following 17865 of 19216 input indexes have `NA` in their classifications:
   1, 2, 4, 5, 6, 7 ... 19212, 19213, 19214, 19215, 19216
 
> x
Error: object 'x' not found

Any idea what is happening here? How should I import a phyloseq object into metacoder? Thanks very much for the help.

**Comment by zachary-foster** [comment]
Hello @ireceptor, It works for me. When did you install? There was an update to `taxa` and `metacoder` about a week ago, and if you installed during the half day or so when `taxa` was updated and `metacoder` was not, it might cause issues. Try reinstalling `metacoder` and see if the example dataset still gives an error. Thanks

**Comment by grabear** [comment]
I got the same error a few days ago, but then I reinstalled taxa and metacoder with `devtools::install_github` and everything worked nicely.

**Comment by ireceptor** [comment]
Hi @zachary-foster @grabear ,

I think my problem is the taxa package. I just reinstalled it and it works great now. Thanks for the help.
