### ISSUE TITLE
Is there a way to label the root without affecting other nodes?

### ISSUE THREAD

**Issue by grabear** [grunwaldlab/metacoder#262]
I'm currently labeling all of my nodes with taxon_ids, because it's easier to read that way for our data.  Is there any way to label the root with the taxon_name, while keeping the other nodes labeled with taxon_ids?

If not that would be an awesome feature.  It can be difficult to discern, which node is the root based on what your node_labels are.

**Comment by zachary-foster** [comment]
Yea, try:

`node_label = ifelse(is_root, taxon_names, taxon_ids)`

**Comment by grabear** [comment]
@zachary-foster I was just looking at my code, and did a nested `ifelse` statement because I only want to label significant significant nodes and the root nodes.

Thanks for the quick response.  Sorry I made an issue out of this.

**Comment by grabear** [comment]
![image](https://user-images.githubusercontent.com/20953530/53206207-f4183e80-35f5-11e9-9fc1-477fa3e713e8.png)

**Comment by zachary-foster** [comment]
no problem, its a common question. I wish all issues were this quick to solve!
