### ISSUE TITLE
make_plot_legend title

### ISSUE THREAD

**Issue by pedrocr83** [grunwaldlab/metacoder#276]
Hi,

Would it be possible to change the title of the heat_tree legend to something other a "Nodes" or "Edges"?

Thank you for your feedback.

**Comment by zachary-foster** [comment]
Hi @pedrocr83, sorry for the delay, I have been traveling the last few weeks.

Not in the `heat_tree` functions right now. It would not be a hard option to add, but I am trying to keep the number of options in the function down ( there are already too many). Eventually I hope to rewrite the heat tree functions to make them more like ggplot2 syntax and take care of a lot of these kind of details then. 

In the mean time, I suggest saving the output as a PDF or SVG, using the `output_file` option and editing the text manually using an PDF/SVG editor like inkscape (free) or adobe illustrator (not free).

**Comment by pedrocr83** [comment]
Hi @zachary-foster ,

any chance this feature exists now? coincidentally it's been a full year to date :) 

Thanks!

**Comment by zachary-foster** [comment]
Hello @pedrocr83,

Thanks for the reminder. I have added the `node_legend_title` and `edge_legend_title` options to `heat_tree` to specify the title for each legend. Reinstall the development version and see if that does what you need:

```r
install.packages("devtools")
devtools::install_github("grunwaldlab/metacoder")
```

**Comment by pedrocr83** [comment]
Thank you!
