### ISSUE TITLE
remove rank label in the qiime export

### ISSUE THREAD

**Issue by lixiaopi1985** [grunwaldlab/metacoder#277]
Hi,

Is there a way to remove the prefix, for example,  "k__" or "D_0" from the label in the heat tree?

I have qiime2 feature table export with taxonomy, I loaded it in with import_biom(), and parse_phyloseq().

Thanks,

Xio

**Comment by zachary-foster** [comment]
Yea, you can use a regex search and replace with functions like `sub`. For example:

```
heat_tree(x, 
          node_label = sub(taxon_names, pattern = '^[a-zA-Z]+_+', replacement = ''), 
          node_size = n_obs, 
          node_color = n_obs)
```

You might need to change the regex pattern depending on what you are trying to remove, but that's the basic idea. 

Also, have you tried `parse_qiime_biom`? It might automatically remove those rank prefixes and store them as `taxon_ranks`; I cant remember.
