### ISSUE TITLE
Is there any way to specify your own set of differentially abundant taxa as input for the heat_tree_matrix function?

### ISSUE THREAD

**Issue by adamsorbie** [grunwaldlab/metacoder#282]
Hi, 

I am analysing data from a study where I have two populations (two groups of mice) and two different environments (two different bodysites) within each population, which unfortunately cannot be compared directly as they were extracted using different methods. Additionally, I have two phenotypes within each group (healthy and sick). 

I would like to create a heattree which compares the sick populations in each environment separately. I already know which taxa are differentially abundant in sick mice but I would like to know whether phylogenetically related taxa are enriched in both each population and environment. 

Is it possible to plot a select list of taxa/otus using the heat_tree_matrix function, or do I have to create my own table which matches the output of the compare groups function but with the OTUs calculated elsewhere?

thanks, 

Adam

**Comment by zachary-foster** [comment]
Hi Adam, 

You would have to create a table with the same format as the output of compare_groups. One way might be to run compare_groups and replace values in the table with your own. If you have ideas for a more convenient input format, feel free to post it here.

**Comment by adamsorbie** [comment]
Thanks a lot for your help, I'll try that.
