### ISSUE TITLE
How to filter taxa with odd names out, but let NA remain in my heattree

### ISSUE THREAD

**Issue by akalichen** [grunwaldlab/metacoder#287]
Hello everyone, 

I want to create a differential heattree to compare microbial communities between the different locations of my reactor. 

Usually, I use 
taxa::filter_taxa(grepl(taxon_names, pattern = "^[a-zA-Z]+$"), reassign_obs = FALSE) %>%
to remove taxa with odd names from my heattree. 

However, I realized that under there are certain unknown taxa (NA) within the Family of Desulfobulbaceae that may be important to my hypothesis. How can I filter all those odd taxa names out of my heattree, but let the NA within Desulfobulbace remain in my tree? 

Or how can I remove odd names such as Unknown_Family, Deepseep 331, etc out of my tree but let the NA remain? 

Thanks very much! Go Beavs!

**Comment by zachary-foster** [comment]
Sorry for the delay. I am preparing to defend my thesis next week and forgot about this. 

Will this work?

```
taxa::filter_taxa(grepl(taxon_names, pattern = "^[a-zA-Z]+$") | is.na(taxon_names), reassign_obs = FALSE)
```

**Comment by akalichen** [comment]
That works! thanks so much! Best wishes with your defense!!!
