### ISSUE TITLE
heat_tree_matrix node labels do not appear

### ISSUE THREAD

**Issue by LeonardosMageiros** [grunwaldlab/metacoder#288]
Hi, 

I am trying to use heat_tree_matrix() to visualize the taxonomy differences in three different countries. 

Using the following command: 

`obj %>%
  taxa::filter_taxa(taxon_ranks == "F", supertaxa = TRUE, reassign_obs = c(diff_table = FALSE)) %>%
  mutate_obs("cleaned_names", gsub(taxon_names, pattern = "\\[|\\]", replacement = "")) %>%
  heat_tree_matrix(data = "diff_table",
                 node_size = n_obs, # n_obs is a function that calculates, in this case, the number of OTUs per taxon
                 node_label = cleaned_names,
                 node_color = log2_median_ratio, # A column from `obj$data$diff_table`
                 node_color_range = diverging_palette(), # The built-in palette for diverging data
                 node_color_trans = "linear", # The default is scaled by circle area
                 node_color_interval = c(-3, 3), # The range of `log2_median_ratio` to display
                 edge_color_interval = c(-3, 3), # The range of `log2_median_ratio` to display
                 node_size_axis_label = "Number of OTUs",
                 node_color_axis_label = "Log2 ratio median proportions",
                 layout = "davidson-harel", # The primary layout algorithm
                 initial_layout = "reingold-tilford", # The layout algorithm that initializes node locations
                 output_file = "differential_heat_tree.pdf") # Saves the plot as a pdf file
`

Gives me the result that I would like but I am not able to see the labels on the nodes on the pairwise comparison trees as I can for the tree on the lower left part of the figure. See screenshot: 

![image](https://user-images.githubusercontent.com/28563735/86592700-9e4ef700-bf9c-11ea-8706-8a285e3efde1.png)

Is there anyway to fix that? If yes is there anyway to remove the tree on the lower left part and only keep the 3 pairwise comparison trees? 

Thank you very much in advance for your time and help. 

Best
Leonardos

**Comment by zachary-foster** [comment]
The default is that the comparison trees are unlabled since the grey "key" tree is meant to function as a legend. You can label the small trees by adding "label_small_trees = TRUE". You can remove the key tree by adding "key_size = 0". Does that do what you want?

**Comment by LeonardosMageiros** [comment]
Yes that exactly what I was looking for. 
Best 
Leonardos
