### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by barveaditya** [grunwaldlab/metacoder#289]
Hello, 

Fantastic work. This is more suggestion than issue. If you haven't already, could you please put up an example of the code used to visualize non-taxonomic data? Say, the Democratic party data from 2016?

Thank you!

**Comment by zachary-foster** [comment]
Hi, thanks!

Its is available here:

https://grunwaldlab.github.io/metacoder_documentation/publication--08--voting.html

**Comment by barveaditya** [comment]
Hi @zachary-foster 

Thanks a million. 

Cheers
Adi
