### ISSUE TITLE
heattree: removing labels from plot without removing OTUs? 

### ISSUE THREAD

**Issue by hbbshulman** [grunwaldlab/metacoder#305]
Hello grunwaldlab, 

Thank you so much for making this fantastic package - I've made a useful and beautiful figure for my study on soil microbiome responses to drought. 

I have a question about plotting taxa names on my heat tree that I hope you can help me with. A lot of my soil bacteria are unclassified at the lower taxonomic ranks - aka lots of "Ambiguous_taxa" and "uncultured bacterium." They are still differentially abundant and significant to my story so I don't want to filter them out of my dataset, but I would like to leave the names off the heattree so it's not cluttered with unnecessary information. 

I have already tried removing these rank names from the taxa string in the otu table or setting them to " ", but in each of these instances the taxmap object creation fails, with the error being "input indexes have `NA` in their classifications" 

Any advice? Thanks so much for your help. -Hannah

<img width="1077" alt="Screen Shot 2021-03-30 at 3 46 52 PM" src="https://user-images.githubusercontent.com/10052155/113066068-c0ae2380-916e-11eb-83c4-a63db896ff53.png">

**Comment by zachary-foster** [comment]
Hello Hannah,

Thanks, I am glad it is useful! 

I usually remove the names at the heat tree creation step, like so:

```r
heat_tree(
  ...,
  node_label = ifelse(is_ambiguous(taxon_names), "", taxon_names),
  ...
)
```

If you come across any unambiguously ambiguous names that `is_ambiguous` does not detect, let me know and I will update the function.

**Comment by hbbshulman** [comment]
Hi Zachary,

Thanks so much for your help - it worked perfectly and my tree is much more legible.
