### ISSUE TITLE
incomplete heattree

### ISSUE THREAD

**Issue by sghignone** [grunwaldlab/metacoder#310]
From the examples you provided, I've learned to build heattrees subsetting taxa at Order level, in this way:
`obj %>%
  taxa::filter_taxa(taxon_ranks == "Order", supertaxa = TRUE) %>%
  heat_tree(node_label = taxon_names,
            node_size = n_obs,
            node_color = ifelse(is.na(padj) | padj > 0.05, 0, log2FoldChange),
            node_color_interval = c(-10, 10), # symmetric interval
           node_color_range [....]`

This is working fine with an object with 2 contrasts, and I correctly get a legend like this:
![image](https://user-images.githubusercontent.com/7242651/117823008-4f818600-b26d-11eb-841f-3aa3174a454c.png)

On the other hand, when I work with an object with 3 contrasts, I end up with a figure with such a legend:
![image](https://user-images.githubusercontent.com/7242651/117824609-ebf85800-b26e-11eb-8e15-a5bca380bbc4.png)
where the counts are zeroed.
This is the code used for the second case:
`set.seed(14497); obj.MZ %>%
  taxa::filter_taxa(taxon_ranks == "Order", supertaxa = TRUE, reassign_obs = FALSE) %>%
  heat_tree_matrix(data = "diff_table",
                   node_size = n_obs,
                   node_label = taxon_names,
                   node_color = ifelse(is.na(padj) | padj > 0.05, 0, log2FoldChange),
                   node_color_range = c("yellow", "gray", "brown"),
                   node_color_trans = "linear",
                   node_color_interval =  c(-10, 10),
                   edge_color_interval =  c(-10, 10),
                   node_size_axis_label = "OTU count",
                   node_color_axis_label = "Log2 ratio median proportions",
                   layout = "da", initial_layout = "re")`

In both cases, the diff table has been obtained with the function calc_diff_abund_deseq2.
I'm attaching the compressed obj.MZ i'm working with, for the second case, for your perusal.
[obj.MZ.RDS.zip](https://github.com/grunwaldlab/metacoder/files/6459623/obj.MZ.RDS.zip)

Thanks a lot in advance.
S.-

**Comment by sghignone** [comment]
so probably this string
`taxa::filter_taxa(taxon_ranks == "F", supertaxa = TRUE, reassign_obs = c(diff_table = FALSE))`
fixed the issue.

Still to understand why the heattree looks like this:
![image](https://user-images.githubusercontent.com/7242651/119120326-72a9f380-ba2c-11eb-9918-691d9351ed82.png)
with borders around the trees...

**Comment by sghignone** [comment]
solved

**Comment by zachary-foster** [comment]
Hello, 

Just saw this now, I must have missed the first post. Sorry for the delay, but I am glad you found a solution.
