### ISSUE TITLE
Error when installing the new version of metacoder

### ISSUE THREAD

**Issue by emankhalaf** [grunwaldlab/metacoder#311]
Hi @grunwald 
I am trying to install the latest version of metacoder using > devtools::install_github("grunwaldlab/metacoder")
and I got this error at the end:
ERROR: dependency ‘svglite’ is not available for package ‘metacoder’
* removing ‘/home/eman/R/x86_64-pc-linux-gnu-library/3.6/metacoder’
Warning messages:
1: In i.p(...) :
  installation of package ‘systemfonts’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘svglite’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘/tmp/RtmpJMFSKg/file348e57268b0b/metacoder_0.3.4.9003.tar.gz’ had non-zero exit status

Your recommendations and help are much appreciated!

**Comment by zachary-foster** [comment]
Hello  Eman, 

Did you see any other errors higher up in the log? Perhaps one mentioning a missing dependency? Try installing svglite by itself and look at what reason it says that it cannot install. Most of the time, there is a missing dependency that has to be installed outside of R. I ran the command that it installed ok.

**Comment by svenyos** [comment]
HI @grunwald 
I also appear to be having - different - installation problems (I've encountered the above issue with svglite before but that is easily rectified by installing it separately).

This is what I get in the console:

Installing package into ‘C:/Users/swedi/OneDrive/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package 'metacoder' ...
** using staged installation
** libs

*** arch - i386
C:/rtools40/mingw64/bin/g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-41~1.0/include" -DNDEBUG  -I'C:/Users/swedi/OneDrive/Documents/R/win-library/4.1/Rcpp/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c RcppExports.cpp -o RcppExports.o
C:/rtools40/mingw64/bin/g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-41~1.0/include" -DNDEBUG  -I'C:/Users/swedi/OneDrive/Documents/R/win-library/4.1/Rcpp/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c repel_boxes.cpp -o repel_boxes.o
C:/rtools40/mingw64/bin/g++ -std=gnu++11 -shared -s -static-libgcc -o metacoder.dll tmp.def RcppExports.o repel_boxes.o -LC:/PROGRA~1/R/R-41~1.0/bin/i386 -lR
C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/PROGRA~1/R/R-41~1.0/bin/i386/R.dll when searching for -lR
C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/PROGRA~1/R/R-41~1.0/bin/i386/R.dll when searching for -lR
C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lR
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'metacoder'
* removing 'C:/Users/swedi/OneDrive/Documents/R/win-library/4.1/metacoder'

Warning message:
In i.p(...) :
  installation of package ‘C:/Users/swedi/AppData/Local/Temp/Rtmp4GoQdW/file6d01b1565f2/metacoder_0.3.4.9003.tar.gz’ had non-zero exit status

Any ideas?

**Comment by svenyos** [comment]
> HI @grunwald
> I also appear to be having - different - installation problems (I've encountered the above issue with svglite before but that is easily rectified by installing it separately).
> 
> This is what I get in the console:
> 
> Installing package into ‘C:/Users/swedi/OneDrive/Documents/R/win-library/4.1’
> (as ‘lib’ is unspecified)
> 
> * installing _source_ package 'metacoder' ...
>   ** using staged installation
>   ** libs
> 
> *** arch - i386
> C:/rtools40/mingw64/bin/g++ -std=gnu++11 -I"C:/PROGRA~1/R/R-41~1.0/include" -DNDEBUG -I'C:/Users/swedi/OneDrive/Documents/R/win-library/4.1/Rcpp/include' -O2 -Wall -mfpmath=sse -msse2 -mstackrealign -c RcppExports.cpp -o RcppExports.o
> C:/rtools40/mingw64/bin/g++ -std=gnu++11 -I"C:/PROGRA~1/R/R-41~1.0/include" -DNDEBUG -I'C:/Users/swedi/OneDrive/Documents/R/win-library/4.1/Rcpp/include' -O2 -Wall -mfpmath=sse -msse2 -mstackrealign -c repel_boxes.cpp -o repel_boxes.o
> C:/rtools40/mingw64/bin/g++ -std=gnu++11 -shared -s -static-libgcc -o metacoder.dll tmp.def RcppExports.o repel_boxes.o -LC:/PROGRA~1/R/R-41~1.0/bin/i386 -lR
> C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/PROGRA~1/R/R-41~1.0/bin/i386/R.dll when searching for -lR
> C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/PROGRA~1/R/R-41~1.0/bin/i386/R.dll when searching for -lR
> C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lR
> collect2.exe: error: ld returned 1 exit status
> no DLL was created
> ERROR: compilation failed for package 'metacoder'
> 
> * removing 'C:/Users/swedi/OneDrive/Documents/R/win-library/4.1/metacoder'
> 
> Warning message:
> In i.p(...) :
> installation of package ‘C:/Users/swedi/AppData/Local/Temp/Rtmp4GoQdW/file6d01b1565f2/metacoder_0.3.4.9003.tar.gz’ had non-zero exit status
> 
> Any ideas?

RESOVLED: Given the mention of repel boxes I uninstalled and then reinstalled _ggrepel_, only to discover it itself has dependencies that include _microbiomeMarker_. which I had removed from the list of packages requiring install (after deleting code pertaining to this package), mistakingly thinking it was no longer needed. 
The problem is resolved if I first install _microbiomeMarker_, then _ggrepel_, and then _Metacoder_

Apologies for unnecessary comment on this issue!

**Comment by emankhalaf** [comment]
> Hello Eman,
> 
> Did you see any other errors higher up in the log? Perhaps one mentioning a missing dependency? Try installing svglite by itself and look at what reason it says that it cannot install. Most of the time, there is a missing dependency that has to be installed outside of R. I ran the command that it installed ok.

As you suggested, I did the following: (installing the development version)
sudo apt install libfontconfig1-dev

Then installed metacoder successfully!
Many thanks!
