### ISSUE TITLE
deseq2 branch

### ISSUE THREAD

**Issue by sghignone** [grunwaldlab/metacoder#325]
Hi Zach!
I'm a user of the dev deseq2 branch but  it's not working since the release of the master v3.5 -- I guess--.
When I install the dev branch with
`devtools::install_github("grunwaldlab/metacoder", ref = "deseq2")`
I get installed the v3.4. With this version,  the function:
`( obj <- metacoder::parse_phyloseq(phyloseq) )`
is not working, and I get the error
`Error: 'ranks_ref' is not an exported object from 'namespace:taxa'`.
To over come this, I install the master version, and the function works, but at this point, `metacoder::calc_diff_abund_deseq2` is not working (obviously, `Error: 'calc_diff_abund_deseq2' is not an exported object from 'namespace:metacoder'`).
Once I've installed the dev branc, I can prepare the obj for the graphical output, but when I run 
```
obj %>%
  taxa::filter_taxa(taxon_ranks == "Order", supertaxa = TRUE) %>%
  heat_tree(node_label = taxon_names,
            node_size = n_obs, [...]
```
I get
`Error: 'filter_taxa' is not an exported object from 'namespace:taxa'
`

I think syncro with current taxa should be revised.
Thanks,

**Comment by zachary-foster** [comment]
Hello,

Thanks for the info. The `calc_diff_abund_deseq2` function has been recently move to the primary development branch, so it can be insatlled with just:

```r
devtools::install_github("grunwaldlab/metacoder")
```
The other issue is that the old version of `taxa` has been reintegrated into `metacoder` until I can finish updaing the new version of `taxa` (we could not have both versions on CRAN at once and metacoder needed to be updated, so this is temporary fix). Therefore the code should be: 

```r
obj %>%
  metacoder::filter_taxa(taxon_ranks == "Order", supertaxa = TRUE) %>%
  heat_tree(node_label = taxon_names,
            node_size = n_obs, [...]
```

Does that solve the problems?

**Comment by sghignone** [comment]
sorted! Thanks

**Comment by davidoctaviobotero** [comment]
Hi Zac,

Thank you for an excellent package. I installed metacodeR with devtools but I could not find this function.

**Comment by zachary-foster** [comment]
Thanks!

I just installed it with:

```r
devtools::install_github("grunwaldlab/metacoder")
```
and was able to see `calc_diff_abund_deseq2`. Can you try installing it again and if you still have the problem include your `sessionInfo()`

**Comment by davidoctaviobotero** [comment]
Hi Zach,

Thank you for the early response. I deleted the issue. Yes, now I can see the function.

Best,
