### ISSUE TITLE
Can we use a uniform color scale in different figs?

### ISSUE THREAD

**Issue by durubing-jn** [grunwaldlab/metacoder#344]
Hi
   Thanks for your useful tool!
   I find that the colo scale always be different in diiferent figs, e.g. 0-73, 0-127, 0-244.  Can I set the uniform scale in different figs? For example, the color scale is from 0 to 300.
![image](https://user-images.githubusercontent.com/44155473/206950601-7b16a661-7731-4ec7-806f-20186ca0c23c.png)

With best regard.

Rubing

**Comment by zachary-foster** [comment]
Thanks! Yes, you can use to the the interval options (e.g. `node_color_interval = c(0, 300)`). See the "Intervals" section of `?heat_tree` for more info.

**Comment by durubing-jn** [comment]
Great, thanks!
