### ISSUE TITLE
primersearch_raw swaps position of forward and reverse primers.

### ISSUE THREAD

**Issue by omarkr8** [grunwaldlab/metacoder#349]
I am stumped about this.

lets say I provide:
Forward primer <- TACAACAT
Reverse primer  <- CATCAGC 
(of which the reverse complement would be GCTGATGA)

and the target region is 
TACAACAT..........GCAGATGA

however the output always swaps the primers.
the f_primer column will have the reverse primer i provide, and vice versa. They still target the correct region though and so amplicon is fine, but the product will be wrong.

the fix i have currently is to input the reverse primer as "forward" and vice versa, this would give me the intended result. but surely not the way to go....
any thoughts?

**Comment by zachary-foster** [comment]
I noticed you closed this. Does this still need attention?
