### ISSUE TITLE
Error in filter_taxa(x, per_taxon_max_change > 2.5, supertaxa = TRUE, : unused arguments

### ISSUE THREAD

**Issue by Low-Maple** [grunwaldlab/metacoder#354]
Hi,
Thank you for the metacoder package.
I'm having an error while trying to run the code you added on Jan. 7, 2021 on issue #297. I have the error with hmp_otus and hm_samples data as well as with my own data.
 At the line :

x <- filter_taxa(x, per_taxon_max_change > 2.5, supertaxa = TRUE, reassign_obs = c(diff_table = FALSE))

I'm having the following error :

Error in filter_taxa(x, per_taxon_max_change > 2.5, supertaxa = TRUE,  : 
  unused arguments (supertaxa = TRUE, reassign_obs = c(diff_table = FALSE))

The resulting heat tree has the taxa that should have been filtered. It worked two days ago, so I'm not sure if I'm the one who did something wrong... 

Thank you very much in advance.

**Comment by zachary-foster** [comment]
Do you have the phyloseq package loaded as well? That package also has a `filter_taxa` function and if you load it after metacoder you will be using the wrong function by mistake.

**Comment by Low-Maple** [comment]
You are right, I had the phyloseq package loaded. It works with metacoder::filter_taxa or by removing the phyloseq package.
Thank you so much for your help.

Best,

**Comment by zachary-foster** [comment]
No problem!
