### ISSUE TITLE
`plot_taxonomy`: add option to set background color

### ISSUE THREAD

**Issue by zachary-foster** [grunwaldlab/metacoder#72]
The default could be transparent or white.
@grunwald @Tabima @zkamvar @knausb: Do you think the background should be white or transparent by default? Thanks for your input!

**Comment by zkamvar** [comment]
White. Backgrounds are not too difficult to remove after the fact.

**Comment by Tabima** [comment]
## Second Zhian’s vote. I personally like white as a BG

Javier F. Tabima R., M. Sc.

Ph. D. Student, 
Botany and Plant Pathology Department.
Oregon State University, 
Corvallis, OR.

Graduate Research Assistant, 
Grunwald lab., 
USDA-ARS,
Corvallis, OR.

people.oregonstate.edu/~tabimaj
grunwaldlab.cgrb.oregonstate.edu/
www.phytopthora-id.org/

**Comment by knausb** [comment]
I would have voted for transparent, it can be a little difficult to set sometimes. Its usually easy to change transparent to white though.

**Comment by zachary-foster** [comment]
Thanks for the feedback everyone! I lean towards transparent as well, since most of the time plots will be put into sideshows or posters that might have non-white backgrounds. But then again, non-white backgrounds might throw off color perception, so I’m conflicted. 

We need a tie-breaker. @grunwald?

**Comment by grunwald** [comment]
Transparent with white as another option.
